author: MohamadReza Koohkan
author_url: https://mohamadreza.codes/
github_url: https://github.com/mohamadrezakoohkan/Dequer
root_url: https://github.com/mohamadrezakoohkan/
module: Dequer
output: docs
theme: apple
