
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :beta do
    increment_build_number(build_number: number_of_commits)
    build_app(scheme: "Dequer",
	      export_method: "ad-hoc")
  end

  lane :deploy  do
    build_app(scheme: "Dequer",
              export_xcargs: "-allowProvisioningUpdates",
	       export_options: {
                method: "ad-hoc"
              })
  end






lane :build do
  gym(
    export_method: "ad-hoc",

    export_xcargs: "-allowProvisioningUpdates",
    export_options: {
      method: "ad-hoc"
    }
  )
end

end
